### ISSUE TITLE
1D formats for IRFs (ARF, RMF), counts vector (PHA)

### ISSUE THREAD

**Issue by joleroi** [gammapy/gamma-astro-data-formats#16]
I am using the OGIP format for 1D spectral analysis in Gammapy. It has, however some slight modifications, so it would be useful to have a page here that is basically a diff to the OGIP standard pages

https://heasarc.gsfc.nasa.gov/docs/heasarc/ofwg/docs/spectra/ogip_92_007/node5.html
http://heasarc.gsfc.nasa.gov/docs/heasarc/caldb/docs/memos/cal_gen_92_002/cal_gen_92_002.html#tth_sEc4
http://heasarc.gsfc.nasa.gov/docs/heasarc/caldb/docs/memos/cal_gen_92_002/cal_gen_92_002.html#tth_sEc3.1

Question: Where should this page live?

Proposal: Split at top level - i.e. IACT IRFs -> 2d IRFs. Add page: 1D IRFs

Do you agree?

**Comment by cdeil** [comment]
+10 to document this here, especially if there are special keywords or comments to be made when doing XSPEC analysis with OGIP-formatted inputs for TeV astronomy.

My proposal would be to leave https://github.com/gammapy/gamma-astro-data-formats/tree/master/source/irfs alone for now (other people are editing the files there at the moment) and to either add a new folder `source/irfs/xspec` or `source/xspec` ... I'm not sure I'd call it 1D IRFs, the PHA files aren't considered IRFs and you want to make notes on that as well, no?

In ~ 1 week when most of the content is accumulated we can discuss proposals to re-structure it better.

**Comment by cdeil** [comment]
@joleroi - I'll try and finish up most of the data format specs before the HESS FITS data telcon on Wednesday. Do you have time for this one and / or EDISP2D or should I do it?

**Comment by joleroi** [comment]
I will start with the EDISP2D

**Comment by joleroi** [comment]
Done, should I start with PHA or are you on it?

**Comment by joleroi** [comment]
Done

**Comment by cdeil** [comment]
Thanks!

**Comment by cdeil** [comment]
@joleroi - I think the most tricky part is EDISP2D and RMF normalisation / interpolation, no?

Can you cross-link the EDISP2D and RMF sections, provide the formula to go back and forth, and say something about normalisation?
For PSF I tried to specify normalisation here:
http://gamma-astro-data-formats.readthedocs.org/en/latest/irfs/psf_table/index.html#normalisation
I don't think it's really useful yet.

If it's not clear what to say about energy resolution normalisation, maybe just leave a TODO for now and make a GH issue?
