### ISSUE TITLE
Presentation at the Astroparticle-Physics Symposium 2022

### ISSUE THREAD

**Issue by maxnoe** [gammapy/gamma-astro-data-formats#198]
Hi all, 

Sorry for the short noticed, but I was asked to give a short presentation on GADF at the "Astroparticle-Physics Symposium 2022" (https://indico.ijclab.in2p3.fr/event/8374/), which in its fourth week starting tomorrow will have a section on open data, open software and interoperability in high energy astroparticle physics.

The talk will be on tuesday, 10-15 minutes long. A talk on the new VODF initiative is scheduled right after.

I will upload slides here as soon as I have them ready (probably this evening or tomorrow around noon) and would be happy for input.

I plan roughly this outline:

* Short History
* Current Status / Release 0.3
* Hand-over to VODF
* Open Issues to be addressed in the scope of VODF

**Comment by maxnoe** [comment]
Here are the slides:

[gadf.pdf](https://github.com/open-gamma-ray-astro/gamma-astro-data-formats/files/10057578/gadf.pdf)

**Comment by lmohrmann** [comment]
Just had a quick look - looks mostly good to me - but would spell out the "VODF" acronym at least once. Thanks!

**Comment by maxnoe** [comment]
@lmohrmann Karl is presenting VODF right after, but yes, will do

**Comment by adonath** [comment]
Thanks @maxnoe! No comments from my side. Should we introduce a single place for slides / presentation on GDAF somewhere?

**Comment by maxnoe** [comment]
I had opened repositories in this organization for the talks I gave... I can add one for this.

**Comment by bkhelifi** [comment]
Great talk, thanks! I have no comment...
Just maybe about p10-11, to be coordinated with Karl in order to avoid repetition (even if their content is great also).

**Comment by maxnoe** [comment]
Hi @bkhelifi I showed Karl the slides this morning, so he knows the content :)

**Comment by cboisson** [comment]
Thanks for this nice talk. 
As you give doi for items slide 8 and 9, you could add the one of the H.E.S.S. data release https://doi.org/10.48550/arXiv.1810.04516.

**Comment by maxnoe** [comment]
Thanks @cboisson, done
